const PROJECT_GANTT_FIXTURES = {
  ZAZZ: {
    projectCode: 'ZAZZ',
    projectName: 'Zazz Board',
    range: {
      startDate: '2026-06-01',
      endDate: '2026-11-20',
    },
    timeline: {
      unit: 'sprint',
      sprintStartDate: '2026-06-01',
      sprintLengthWeeks: 2,
      sprintLabelPrefix: 'Sprint',
      weekLabelPrefix: 'W',
    },
    rows: [
      {
        id: 'milestone:default',
        entityType: 'milestone',
        labelKey: 'gantt.defaultMilestone',
        labelParams: {},
        startDate: '2026-06-01',
        endDate: '2026-08-14',
        status: 'IN_PROGRESS',
        progress: 35,
        completed: false,
        isDefault: true,
      },
      {
        id: 'deliverable:default-docs',
        entityType: 'deliverable',
        parentId: 'milestone:default',
        deliverableId: 'default-docs',
        deliverableCode: 'ZAZZ-6',
        displayName: 'Multiple-agent token rollout',
        startDate: '2026-06-03',
        endDate: '2026-06-12',
        status: 'IN_PROGRESS',
        progress: 58,
        completed: false,
        taskCount: 3,
        lazyTasks: true,
      },
      {
        id: 'deliverable:default-tags',
        entityType: 'deliverable',
        parentId: 'milestone:default',
        deliverableId: 'default-tags',
        deliverableCode: 'ZAZZ-3',
        displayName: 'Fix tag validation bug',
        startDate: '2026-06-05',
        endDate: '2026-06-07',
        status: 'DONE',
        progress: 100,
        completed: true,
        taskCount: 2,
        lazyTasks: true,
      },
      {
        id: 'deliverable:default-i18n',
        entityType: 'deliverable',
        parentId: 'milestone:default',
        deliverableId: 'default-i18n',
        deliverableCode: 'ZAZZ-7',
        displayName: 'Locale coverage cleanup',
        startDate: '2026-06-10',
        endDate: '2026-06-21',
        status: 'PLANNING',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'deliverable:default-audit',
        entityType: 'deliverable',
        parentId: 'milestone:default',
        deliverableId: 'default-audit',
        deliverableCode: 'ZAZZ-8',
        displayName: 'Audit event naming pass',
        startDate: '2026-06-17',
        endDate: '2026-06-28',
        status: 'PLANNING',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'deliverable:default-owner-settings',
        entityType: 'deliverable',
        parentId: 'milestone:default',
        deliverableId: 'default-owner-settings',
        deliverableCode: 'ZAZZ-9',
        displayName: 'Project owner settings polish',
        startDate: '2026-06-24',
        endDate: '2026-07-05',
        status: 'PLANNING',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'deliverable:default-api-docs',
        entityType: 'deliverable',
        parentId: 'milestone:default',
        deliverableId: 'default-api-docs',
        deliverableCode: 'ZAZZ-10',
        displayName: 'Mock API contract examples',
        startDate: '2026-07-01',
        endDate: '2026-07-12',
        status: 'PLANNING',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'deliverable:default-qa',
        entityType: 'deliverable',
        parentId: 'milestone:default',
        deliverableId: 'default-qa',
        deliverableCode: 'ZAZZ-11',
        displayName: 'Gantt QA smoke checklist',
        startDate: '2026-07-15',
        endDate: '2026-08-01',
        status: 'PLANNING',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'milestone:one',
        entityType: 'milestone',
        labelKey: 'gantt.numberedMilestone',
        labelParams: { number: 1 },
        startDate: '2026-06-15',
        endDate: '2026-07-03',
        status: 'IN_PROGRESS',
        progress: 82,
        completed: false,
      },
      {
        id: 'deliverable:m1-d1',
        entityType: 'deliverable',
        parentId: 'milestone:one',
        deliverableId: 'm1-d1',
        deliverableCode: 'M1-D1',
        displayName: 'SVAR Gantt UI and mocked contract',
        startDate: '2026-06-15',
        endDate: '2026-06-26',
        status: 'DONE',
        progress: 100,
        completed: true,
        taskCount: 4,
        lazyTasks: true,
      },
      {
        id: 'deliverable:m1-d2',
        entityType: 'deliverable',
        parentId: 'milestone:one',
        deliverableId: 'm1-d2',
        deliverableCode: 'M1-D2',
        displayName: 'Gantt API and database persistence',
        startDate: '2026-06-29',
        endDate: '2026-07-03',
        status: 'IN_REVIEW',
        progress: 65,
        completed: false,
        taskCount: 3,
        lazyTasks: true,
      },
      {
        id: 'milestone:two',
        entityType: 'milestone',
        labelKey: 'gantt.numberedMilestone',
        labelParams: { number: 2 },
        startDate: '2026-07-06',
        endDate: '2026-07-31',
        status: 'PENDING',
        progress: 18,
        completed: false,
      },
      {
        id: 'deliverable:m2-editor',
        entityType: 'deliverable',
        parentId: 'milestone:two',
        deliverableId: 'm2-editor',
        deliverableCode: 'M2-D1',
        displayName: 'Milestone editor hardening',
        startDate: '2026-07-06',
        endDate: '2026-07-17',
        status: 'PLANNING',
        progress: 10,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'deliverable:m2-reassign',
        entityType: 'deliverable',
        parentId: 'milestone:two',
        deliverableId: 'm2-reassign',
        deliverableCode: 'M2-D2',
        displayName: 'Drag/drop milestone reassignment',
        startDate: '2026-07-20',
        endDate: '2026-07-31',
        status: 'PLANNING',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'milestone:three',
        entityType: 'milestone',
        labelKey: 'gantt.numberedMilestone',
        labelParams: { number: 3 },
        startDate: '2026-08-03',
        endDate: '2026-08-28',
        status: 'PENDING',
        progress: 0,
        completed: false,
      },
      {
        id: 'deliverable:m3-dependencies',
        entityType: 'deliverable',
        parentId: 'milestone:three',
        deliverableId: 'm3-dependencies',
        deliverableCode: 'M3-D1',
        displayName: 'Dependency editing and schedule helpers',
        startDate: '2026-08-03',
        endDate: '2026-08-14',
        status: 'PLANNING',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'deliverable:m3-filters',
        entityType: 'deliverable',
        parentId: 'milestone:three',
        deliverableId: 'm3-filters',
        deliverableCode: 'M3-D2',
        displayName: 'Timeline filters and risk markers',
        startDate: '2026-08-17',
        endDate: '2026-08-28',
        status: 'PLANNING',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'milestone:four',
        entityType: 'milestone',
        labelKey: 'gantt.numberedMilestone',
        labelParams: { number: 4 },
        startDate: '2026-08-31',
        endDate: '2026-09-25',
        status: 'PLANNING',
        progress: 0,
        completed: false,
      },
      {
        id: 'deliverable:m4-realtime',
        entityType: 'deliverable',
        parentId: 'milestone:four',
        deliverableId: 'm4-realtime',
        deliverableCode: 'M4-D1',
        displayName: 'Realtime row patching and task rollups',
        startDate: '2026-08-31',
        endDate: '2026-09-11',
        status: 'PROPOSED',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'deliverable:m4-capacity',
        entityType: 'deliverable',
        parentId: 'milestone:four',
        deliverableId: 'm4-capacity',
        deliverableCode: 'M4-D2',
        displayName: 'Agent capacity overlays',
        startDate: '2026-09-14',
        endDate: '2026-09-25',
        status: 'PROPOSED',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'milestone:five',
        entityType: 'milestone',
        labelKey: 'gantt.numberedMilestone',
        labelParams: { number: 5 },
        startDate: '2026-09-28',
        endDate: '2026-10-23',
        status: 'PLANNING',
        progress: 0,
        completed: false,
      },
      {
        id: 'deliverable:m5-planning-api',
        entityType: 'deliverable',
        parentId: 'milestone:five',
        deliverableId: 'm5-planning-api',
        deliverableCode: 'M5-D1',
        displayName: 'Planning API for milestone assignment',
        startDate: '2026-09-28',
        endDate: '2026-10-09',
        status: 'PROPOSED',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'deliverable:m5-bulk-move',
        entityType: 'deliverable',
        parentId: 'milestone:five',
        deliverableId: 'm5-bulk-move',
        deliverableCode: 'M5-D2',
        displayName: 'Bulk milestone moves and audit history',
        startDate: '2026-10-12',
        endDate: '2026-10-23',
        status: 'PROPOSED',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'milestone:six',
        entityType: 'milestone',
        labelKey: 'gantt.numberedMilestone',
        labelParams: { number: 6 },
        startDate: '2026-10-26',
        endDate: '2026-11-20',
        status: 'PLANNING',
        progress: 0,
        completed: false,
      },
      {
        id: 'deliverable:m6-reporting',
        entityType: 'deliverable',
        parentId: 'milestone:six',
        deliverableId: 'm6-reporting',
        deliverableCode: 'M6-D1',
        displayName: 'Milestone reporting snapshots',
        startDate: '2026-10-26',
        endDate: '2026-11-06',
        status: 'PROPOSED',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
      {
        id: 'deliverable:m6-export',
        entityType: 'deliverable',
        parentId: 'milestone:six',
        deliverableId: 'm6-export',
        deliverableCode: 'M6-D2',
        displayName: 'Roadmap export and stakeholder view',
        startDate: '2026-11-09',
        endDate: '2026-11-20',
        status: 'PROPOSED',
        progress: 0,
        completed: false,
        taskCount: 0,
        lazyTasks: false,
      },
    ],
    links: [
      {
        id: 'link:default-docs-to-m1-d1',
        sourceId: 'deliverable:default-docs',
        targetId: 'deliverable:m1-d1',
        type: 'e2s',
        relationType: 'DEPENDS_ON',
      },
      {
        id: 'link:m1-d1-to-m1-d2',
        sourceId: 'deliverable:m1-d1',
        targetId: 'deliverable:m1-d2',
        type: 'e2s',
        relationType: 'DEPENDS_ON',
      },
      {
        id: 'link:m1-d2-to-m2-editor',
        sourceId: 'deliverable:m1-d2',
        targetId: 'deliverable:m2-editor',
        type: 'e2s',
        relationType: 'DEPENDS_ON',
      },
      {
        id: 'link:m2-reassign-to-m3-dependencies',
        sourceId: 'deliverable:m2-reassign',
        targetId: 'deliverable:m3-dependencies',
        type: 'e2s',
        relationType: 'DEPENDS_ON',
      },
      {
        id: 'link:m4-realtime-to-m5-planning-api',
        sourceId: 'deliverable:m4-realtime',
        targetId: 'deliverable:m5-planning-api',
        type: 'e2s',
        relationType: 'DEPENDS_ON',
      },
      {
        id: 'link:m5-bulk-move-to-m6-reporting',
        sourceId: 'deliverable:m5-bulk-move',
        targetId: 'deliverable:m6-reporting',
        type: 'e2s',
        relationType: 'DEPENDS_ON',
      },
    ],
  },
};

const PROJECT_GANTT_SETTINGS_FIXTURES = {
  ZAZZ: {
    projectCode: 'ZAZZ',
    timelineMode: 'sprint',
    showDateLabels: false,
    showDefaultMilestone: false,
    showMonthHeader: true,
    showSprintHeader: true,
    showWeekHeader: true,
    periodStartDate: '2026-06-01',
    sprintLengthWeeks: 2,
    periodNumberStart: 1,
    sprintLabelPrefix: 'Sprint',
    weekLabelPrefix: 'W',
  },
};

const DELIVERABLE_TASK_FIXTURES = {
  ZAZZ: {
    'default-docs': {
      projectCode: 'ZAZZ',
      deliverableId: 'default-docs',
      rows: [
        {
          id: 'task:token-schema',
          entityType: 'task',
          parentId: 'deliverable:default-docs',
          displayName: 'Confirm agent token project scope',
          startDate: '2026-06-03',
          endDate: '2026-06-05',
          status: 'COMPLETED',
          progress: 100,
          completed: true,
        },
        {
          id: 'task:token-ui',
          entityType: 'task',
          parentId: 'deliverable:default-docs',
          displayName: 'Expose token management panel',
          startDate: '2026-06-08',
          endDate: '2026-06-10',
          status: 'IN_PROGRESS',
          progress: 60,
          completed: false,
        },
        {
          id: 'task:token-tests',
          entityType: 'task',
          parentId: 'deliverable:default-docs',
          displayName: 'Add route and UI regression checks',
          startDate: '2026-06-11',
          endDate: '2026-06-12',
          status: 'READY',
          progress: 0,
          completed: false,
        },
      ],
      links: [
        {
          id: 'link:token-schema-token-ui',
          sourceId: 'task:token-schema',
          targetId: 'task:token-ui',
          type: 'e2s',
          relationType: 'DEPENDS_ON',
        },
        {
          id: 'link:token-ui-token-tests',
          sourceId: 'task:token-ui',
          targetId: 'task:token-tests',
          type: 'e2s',
          relationType: 'DEPENDS_ON',
        },
      ],
    },
    'm1-d1': {
      projectCode: 'ZAZZ',
      deliverableId: 'm1-d1',
      rows: [
        {
          id: 'task:gantt-contract',
          entityType: 'task',
          parentId: 'deliverable:m1-d1',
          displayName: 'Define mocked Gantt JSON contract',
          startDate: '2026-06-15',
          endDate: '2026-06-17',
          status: 'COMPLETED',
          progress: 100,
          completed: true,
        },
        {
          id: 'task:gantt-widget',
          entityType: 'task',
          parentId: 'deliverable:m1-d1',
          displayName: 'Render SVAR hierarchy and links',
          startDate: '2026-06-18',
          endDate: '2026-06-22',
          status: 'COMPLETED',
          progress: 100,
          completed: true,
        },
        {
          id: 'task:gantt-routing',
          entityType: 'task',
          parentId: 'deliverable:m1-d1',
          displayName: 'Wire project landing and view switcher',
          startDate: '2026-06-23',
          endDate: '2026-06-24',
          status: 'COMPLETED',
          progress: 100,
          completed: true,
        },
        {
          id: 'task:gantt-evidence',
          entityType: 'task',
          parentId: 'deliverable:m1-d1',
          displayName: 'Capture run-log evidence',
          startDate: '2026-06-25',
          endDate: '2026-06-26',
          status: 'COMPLETED',
          progress: 100,
          completed: true,
        },
      ],
      links: [
        {
          id: 'link:gantt-contract-widget',
          sourceId: 'task:gantt-contract',
          targetId: 'task:gantt-widget',
          type: 'e2s',
          relationType: 'DEPENDS_ON',
        },
        {
          id: 'link:gantt-widget-routing',
          sourceId: 'task:gantt-widget',
          targetId: 'task:gantt-routing',
          type: 'e2s',
          relationType: 'DEPENDS_ON',
        },
        {
          id: 'link:gantt-routing-evidence',
          sourceId: 'task:gantt-routing',
          targetId: 'task:gantt-evidence',
          type: 'e2s',
          relationType: 'DEPENDS_ON',
        },
      ],
    },
    'm1-d2': {
      projectCode: 'ZAZZ',
      deliverableId: 'm1-d2',
      rows: [
        {
          id: 'task:gantt-schema',
          entityType: 'task',
          parentId: 'deliverable:m1-d2',
          displayName: 'Draft milestone persistence schema',
          startDate: '2026-06-29',
          endDate: '2026-06-30',
          status: 'IN_REVIEW',
          progress: 70,
          completed: false,
        },
        {
          id: 'task:gantt-api-service',
          entityType: 'task',
          parentId: 'deliverable:m1-d2',
          displayName: 'Project Gantt projection service',
          startDate: '2026-07-01',
          endDate: '2026-07-02',
          status: 'IN_PROGRESS',
          progress: 45,
          completed: false,
        },
        {
          id: 'task:gantt-db-tests',
          entityType: 'task',
          parentId: 'deliverable:m1-d2',
          displayName: 'Contract tests against seeded data',
          startDate: '2026-07-02',
          endDate: '2026-07-03',
          status: 'PLANNING',
          progress: 0,
          completed: false,
        },
      ],
      links: [
        {
          id: 'link:gantt-schema-api-service',
          sourceId: 'task:gantt-schema',
          targetId: 'task:gantt-api-service',
          type: 'e2s',
          relationType: 'DEPENDS_ON',
        },
        {
          id: 'link:gantt-api-service-db-tests',
          sourceId: 'task:gantt-api-service',
          targetId: 'task:gantt-db-tests',
          type: 'e2s',
          relationType: 'DEPENDS_ON',
        },
      ],
    },
  },
};

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function getTimelineFromSettings(settings) {
  const unitMap = {
    dates: 'date',
    weeks: 'week',
    sprint: 'sprint',
  };

  return {
    unit: unitMap[settings.timelineMode] || 'sprint',
    showDateLabels: settings.showDateLabels,
    showDefaultMilestone: settings.showDefaultMilestone,
    showMonthHeader: settings.showMonthHeader,
    showSprintHeader: settings.showSprintHeader,
    showWeekHeader: settings.showWeekHeader,
    periodStartDate: settings.periodStartDate,
    periodNumberStart: settings.periodNumberStart,
    sprintStartDate: settings.periodStartDate,
    sprintLengthWeeks: settings.sprintLengthWeeks,
    sprintLabelPrefix: settings.sprintLabelPrefix,
    weekLabelPrefix: settings.weekLabelPrefix,
  };
}

export function getMockProjectGantt(projectCode) {
  const normalizedProjectCode = String(projectCode).toUpperCase();
  const fixture = PROJECT_GANTT_FIXTURES[normalizedProjectCode];
  if (!fixture) return null;

  const gantt = clone(fixture);
  const settings = PROJECT_GANTT_SETTINGS_FIXTURES[normalizedProjectCode];
  if (settings) {
    gantt.timeline = getTimelineFromSettings(settings);
  }

  return gantt;
}

export function getMockDeliverableGanttTasks(projectCode, deliverableId) {
  const projectFixtures = DELIVERABLE_TASK_FIXTURES[String(projectCode).toUpperCase()];
  const fixture = projectFixtures?.[String(deliverableId)];
  return fixture ? clone(fixture) : null;
}

export function getMockProjectGanttSettings(projectCode) {
  const settings = PROJECT_GANTT_SETTINGS_FIXTURES[String(projectCode).toUpperCase()];
  return settings ? clone(settings) : null;
}

export function updateMockProjectGanttSettings(projectCode, settingsPatch) {
  const normalizedProjectCode = String(projectCode).toUpperCase();
  const existing = PROJECT_GANTT_SETTINGS_FIXTURES[normalizedProjectCode];
  if (!existing) return null;

  PROJECT_GANTT_SETTINGS_FIXTURES[normalizedProjectCode] = {
    ...existing,
    ...settingsPatch,
    projectCode: normalizedProjectCode,
  };

  return clone(PROJECT_GANTT_SETTINGS_FIXTURES[normalizedProjectCode]);
}
